Proje/src/java/UsersBean.java
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.faces.bean.ManagedBean;
import javax.sql.rowset.CachedRowSet;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

@ManagedBean( name="usersBean" )
 
public class UsersBean
{
     
    DataSource dataSource;
    
    public UsersBean()
    {
        try
        {
            Context ctx = new InitialContext();
            dataSource = (DataSource) ctx.lookup("jdbc/ArabaKiralamaDB");
        }
        catch (NamingException e) 
        {
            e.printStackTrace();
        }
    }

    public ResultSet getKullanicilar() throws SQLException
    {
            
            if ( dataSource == null )
                throw new SQLException( "Unable to obtain DataSource" );

           
            Connection connection = dataSource.getConnection();

            
            if ( connection == null )
            throw new SQLException( "Unable to connect to DataSource" );

            try
            {

            
                PreparedStatement luksAraclariGetir = connection.prepareStatement(
                "SELECT * FROM " +
                "Users");
                 CachedRowSet rowSet = new com.sun.rowset.CachedRowSetImpl();
                 rowSet.populate( luksAraclariGetir.executeQuery() );
                 return rowSet;
            }
            finally
            {
                connection.close(); 
            } 
    } 
     
}

Proje/web/EkonomikAraclarTablosu_ekle.xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>KÜBRA AÇIKGÖZ</title>
        <h:outputStylesheet library="css" name="demo.css"/>
    </h:head>
<h:body>
<div class="ustcizgi">
</div>

<div class="clearfix"></div>

<div class="ustserit">
	<div class="logo">
		<img src="resources/images/logo1.png"/>
	</div>
</div>

<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="serit">
	<ul id="menu">
		<li><a href="index.xhtml">ANASAYFA</a></li>
		<li>
			<a href="#">ARAÇ FİLOMUZ</a>
			<ul>
				<li><a href="luxarac.html">LUX ARAÇ</a></li>
				<li><a href="jeep.html">JEEP KİRALAMA</a></li>
				<li><a href="ekonomiklux.html">EKONOMİK LÜX</a></li>
				<li><a href="ekonomik.html">EKONOMİK</a></li>
			</ul>
		</li>
		<li>
			<a href="#">KİRALAMA DETAYI</a>
			<ul>
				<li><a href="ehliyetyas.html">EHLİYET VE YAŞ</a></li>
				<li><a href="kiralamakosullari.html">KİRALAMA KOŞULLARI</a></li>
				<li><a href="teslimat.html">TESLİMAT</a></li>
				<li><a href="sigorta.html">SİGORTA</a></li>
			</ul>
		</li>
		<li><a href="hakkimizda.html">HAKKIMIZDA</a></li>
		<li><a href="iletisim.html">İLETİŞİM</a></li>
	</ul>
</div>
    <h1>Ekonomik Araçlar Tablosu : Araç Ekle</h1>
 <h:form>
 <h:panelGrid columns="3">
     
 <h:outputText value="Marka :"/>
 <h:inputText id="markaInputText" required="true"
 requiredMessage="Lütfen bir marka girin"
 value="#{databaseBean.marka}" maxlength="30"/>
 <h:message for="markaInputText"/>
 
 <h:outputText value="Kiralama Modeli:"/>
 <h:inputText id="modelInputText" required="true"
 requiredMessage="Lütfen bir model girin"
 value="#{databaseBean.kiralamaModeli}" maxlength="30"/>
 <h:message for="modelInputText"/>
 
 <h:outputText value="Yıl:"/>
 <h:inputText id="yilInputText" required="true"
 requiredMessage="Lütfen yıl girin"
 value="#{databaseBean.yil}" maxlength="2014"/>
 <h:message for="yilInputText" />
 
 <h:outputText value="Motor:"/>
 <h:inputText id="motorInputText" required="true"
 requiredMessage="Please enter state"
 value="#{databaseBean.motor}" maxlength="30"/>
 <h:message for="motorInputText"/>
 
<h:outputText value="Vites:"/>
 <h:inputText id="vitesInputText" required="true"
requiredMessage="Lütfen vites itip giriniz."
value="#{databaseBean.vites}" maxlength="30"/>
 <h:message for="vitesInputText"/>
 
 <h:outputText value="Kasa Tipi:"/>
 <h:inputText id="kasaTipiInputText" required="true"
 requiredMessage="Lütfen kasa tipi girin"
 value="#{databaseBean.kasaTipi}" maxlength="30"/>
 <h:message for="kasaTipiInputText"/>
 
 <h:outputText value="Yakıt Tipi:"/>
 <h:inputText id="yakitTipiInputText" required="true"
 requiredMessage="Lütfen yakıt tipi girin"
 value="#{databaseBean.yakitTipi}" maxlength="30"/>
 <h:message for="yakitTipiInputText"/>
 
 <h:outputText value="Stok"/>
 <h:inputText id="stokInputText" required="true"
 requiredMessage="Lütfen stok girin"
 value="#{databaseBean.stok}" maxlength="1500"/>
 <h:message for="stokInputText"/>
 
 <h:outputText value="Günlük Kiralama Bedeli"/>
 <h:inputText id="fiyatInputText" required="true"
 requiredMessage="Lütfen TL bazında fiyat girin"
 value="#{databaseBean.fiyat}" maxlength="1000"/>
 <h:message for="fiyatInputText"/>
 
 </h:panelGrid>
     
     <h:commandButton value="Aracı Ekle" action="#{databaseBean.save}" >
         <f:setPropertyActionListener target="#{databaseBean.tabloAdi}" value="Ekonomik" />
     </h:commandButton>
<h:commandButton value="Temizle" type="reset"/>

 </h:form>
 <h:outputLink value="#{databaseBean.donus()}">Ekonomik Araç Tablosuna Geri Dön</h:outputLink>
<div class="clearfix"></div>
<div class="footer">
	Copyright  2014 | Tüm hakları İssizzler' e saklıdır.
</div>
<div class="clearfix"></div>
</h:body>
</html>

Proje/web/KullanicilarTablosu.xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>KÜBRA AÇIKGÖZ</title>
        <h:outputStylesheet library="css" name="demo.css"/>
    </h:head>
<h:body>
<div class="ustcizgi">
</div>

<div class="clearfix"></div>

<div class="ustserit">
	<div class="logo">
		<img src="resources/images/logo1.png"/>
	</div>
</div>

<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="serit">
	<ul id="menu">
		<li><a href="index.xhtml">ANASAYFA</a></li>
		<li>
			<a href="#">ARAÇ FİLOMUZ</a>
			<ul>
				<li><a href="luxarac.html">LUX ARAÇ</a></li>
				<li><a href="jeep.html">JEEP KİRALAMA</a></li>
				<li><a href="ekonomiklux.html">EKONOMİK LÜX</a></li>
				<li><a href="ekonomik.html">EKONOMİK</a></li>
			</ul>
		</li>
		<li>
			<a href="#">KİRALAMA DETAYI</a>
			<ul>
				<li><a href="ehliyetyas.html">EHLİYET VE YAŞ</a></li>
				<li><a href="kiralamakosullari.html">KİRALAMA KOŞULLARI</a></li>
				<li><a href="teslimat.html">TESLİMAT</a></li>
				<li><a href="sigorta.html">SİGORTA</a></li>
			</ul>
		</li>
		<li><a href="hakkimizda.html">HAKKIMIZDA</a></li>
		<li><a href="iletisim.html">İLETİŞİM</a></li>
	</ul>
</div>
    <h:form style="">
           <h3>Kullanıcılar Tablosu</h3>
 
            <h:dataTable value="#{usersBean.kullanicilar}" var="kullanici"
           border="1" cellpadding="5" cellspacing="0">
           <h:column>
           <f:facet name="header">Kullanıcı Adı</f:facet>
           #{kullanici.KullaniciAdi}
           </h:column>
            <h:column>
            <f:facet name="header">Şifre</f:facet>
           #{kullanici.Şifre}
            </h:column>
            <h:column>
            <f:facet name="header">Ad</f:facet>
           #{kullanici.Ad}
            </h:column>
            <h:column>
            <f:facet name="header">Soyad</f:facet>
           #{kullanici.Soyad}
            </h:column>
            <h:column>
            <f:facet name="header">Email</f:facet>
           #{kullanici.Email}
            </h:column>
            <h:column>
            <f:facet name="header"></f:facet>
           #{kullanici.Telefon}
            </h:column>
            </h:dataTable>

                
            </h:form> 
<div class="clearfix"></div>
<div class="footer">
	Copyright  2014 | Tüm hakları İssizzler' e saklıdır.
</div>
<div class="clearfix"></div>
</h:body>
</html>

Proje/web/LuksAraclarTablosu_ekle.xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>KÜBRA AÇIKGÖZ</title>
        <h:outputStylesheet library="css" name="demo.css"/>
    </h:head>
<h:body>
<div class="ustcizgi">
</div>

<div class="clearfix"></div>

<div class="ustserit">
	<div class="logo">
		<img src="resources/images/logo1.png"/>
	</div>
</div>

<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="serit">
	<ul id="menu">
		<li><a href="index.xhtml">ANASAYFA</a></li>
		<li>
			<a href="#">ARAÇ FİLOMUZ</a>
			<ul>
				<li><a href="luxarac.html">LUX ARAÇ</a></li>
				<li><a href="jeep.html">JEEP KİRALAMA</a></li>
				<li><a href="ekonomiklux.html">EKONOMİK LÜX</a></li>
				<li><a href="ekonomik.html">EKONOMİK</a></li>
			</ul>
		</li>
		<li>
			<a href="#">KİRALAMA DETAYI</a>
			<ul>
				<li><a href="ehliyetyas.html">EHLİYET VE YAŞ</a></li>
				<li><a href="kiralamakosullari.html">KİRALAMA KOŞULLARI</a></li>
				<li><a href="teslimat.html">TESLİMAT</a></li>
				<li><a href="sigorta.html">SİGORTA</a></li>
			</ul>
		</li>
		<li><a href="hakkimizda.html">HAKKIMIZDA</a></li>
		<li><a href="iletisim.html">İLETİŞİM</a></li>
	</ul>
</div>
    <h1>Luks Araçlar Tablosu : Araç Ekle</h1>
 <h:form>
 <h:panelGrid columns="3">
     
 <h:outputText value="Marka :"/>
 <h:inputText id="markaInputText" required="true"
 requiredMessage="Lütfen bir marka girin"
 value="#{databaseBean.marka}" maxlength="30"/>
 <h:message for="markaInputText"/>
 
 <h:outputText value="Kiralama Modeli:"/>
 <h:inputText id="modelInputText" required="true"
 requiredMessage="Lütfen bir model girin"
 value="#{databaseBean.kiralamaModeli}" maxlength="30"/>
 <h:message for="modelInputText"/>
 
 <h:outputText value="Yıl:"/>
 <h:inputText id="yilInputText" required="true"
 requiredMessage="Lütfen yıl girin"
 value="#{databaseBean.yil}" maxlength="2014"/>
 <h:message for="yilInputText" />
 
 <h:outputText value="Motor:"/>
 <h:inputText id="motorInputText" required="true"
 requiredMessage="Please enter state"
 value="#{databaseBean.motor}" maxlength="30"/>
 <h:message for="motorInputText"/>
 
<h:outputText value="Vites:"/>
 <h:inputText id="vitesInputText" required="true"
requiredMessage="Lütfen vites itip giriniz."
value="#{databaseBean.vites}" maxlength="30"/>
 <h:message for="vitesInputText"/>
 
 <h:outputText value="Kasa Tipi:"/>
 <h:inputText id="kasaTipiInputText" required="true"
 requiredMessage="Lütfen kasa tipi girin"
 value="#{databaseBean.kasaTipi}" maxlength="30"/>
 <h:message for="kasaTipiInputText"/>
 
 <h:outputText value="Yakıt Tipi:"/>
 <h:inputText id="yakitTipiInputText" required="true"
 requiredMessage="Lütfen yakıt tipi girin"
 value="#{databaseBean.yakitTipi}" maxlength="30"/>
 <h:message for="yakitTipiInputText"/>
 
 <h:outputText value="Stok"/>
 <h:inputText id="stokInputText" required="true"
 requiredMessage="Lütfen stok girin"
 value="#{databaseBean.stok}" maxlength="1500"/>
 <h:message for="stokInputText"/>
 
 <h:outputText value="Günlük Kiralama Bedeli"/>
 <h:inputText id="fiyatInputText" required="true"
 requiredMessage="Lütfen TL bazında fiyat girin"
 value="#{databaseBean.fiyat}" maxlength="1000"/>
 <h:message for="fiyatInputText"/>
 
 </h:panelGrid>
     
     <h:commandButton value="Aracı Ekle" action="#{databaseBean.save}" >
         <f:setPropertyActionListener target="#{databaseBean.tabloAdi}" value="Luks" />
     </h:commandButton>
<h:commandButton value="Temizle" type="reset"/>

 </h:form>
 <h:outputLink value="#{databaseBean.donus()}">Luks Araç Tablosuna Geri Dön</h:outputLink>
<div class="clearfix"></div>
<div class="footer">
	Copyright  2014 | Tüm hakları İssizzler' e saklıdır.
</div>
<div class="clearfix"></div>
</h:body>
</html>

Proje/web/resime4.xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>KÜBRA AÇIKGÖZ</title>
        <h:outputStylesheet library="css" name="demo.css"/>
    </h:head>
<h:body>
<div class="ustcizgi">
</div>

<div class="clearfix"></div>

<div class="ustserit">
	<div class="logo">
		<img src="resources/images/logo1.png"/>
	</div>
</div>

<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="serit">
	<ul id="menu">
		<li><a href="index.xhtml">ANASAYFA</a></li>
		<li>
			<a href="#">ARAÇ FİLOMUZ</a>
			<ul>
				<li><a href="luxarac.html">LUX ARAÇ</a></li>
				<li><a href="jeep.html">JEEP KİRALAMA</a></li>
				<li><a href="ekonomiklux.html">EKONOMİK LÜX</a></li>
				<li><a href="ekonomik.html">EKONOMİK</a></li>
			</ul>
		</li>
		<li>
			<a href="#">KİRALAMA DETAYI</a>
			<ul>
				<li><a href="ehliyetyas.html">EHLİYET VE YAŞ</a></li>
				<li><a href="kiralamakosullari.html">KİRALAMA KOŞULLARI</a></li>
				<li><a href="teslimat.html">TESLİMAT</a></li>
				<li><a href="sigorta.html">SİGORTA</a></li>
			</ul>
		</li>
		<li><a href="hakkimizda.html">HAKKIMIZDA</a></li>
		<li><a href="iletisim.html">İLETİŞİM</a></li>
	</ul>
</div>
<div class="clearfix"></div>
<div class="iletisim">
	<h1>EKONOMİK ARAÇ</h1>
	<div class="iletisim_form">
		<h2>Hyundai Era</h2>
                <img class="" alt="" src="resources/images/resime4.jpg" />
	</div>
	<div class="iletisim_bilgi">
        <br />
<h2>ARAÇ ÖZELLİKLERİ :</h2>		
<p>Marka:  AUDİ</p>	
<p>Kiralama Model: Hyundail Era</p>	
<p>Yıl:    2013</p>	
<p>Motor:  2200</p>	
<p>Vites:  Tiptronic Vites</p>	
<p>Kasa Tipi: Sedan</p>
<p>Yakıt Tipi: Dizel</p>
   <br />   <br />
<div class="kirala" style="margin-left:5px;">
            <h:form>
                <h:panelGrid style="width:60px; height:100px;" bgcolor="#e6edfd" columns="3" border="0">
                    <f:facet name="header">
                        <h:outputText value="Auris"/>
                    </f:facet>
                   <h:outputText value="GÜN:"/>
              
                      <h:selectOneMenu value = "#{kiralaBean.gun}">
                        <f:selectItem itemValue="1" itemLabel="1 Gün" />
                        <f:selectItem itemValue="2" itemLabel="2 Gün" />
                        <f:selectItem itemValue="3" itemLabel="3 Gün" />
                        <f:selectItem itemValue="4" itemLabel="4 Gün" />
                        <f:selectItem itemValue="5" itemLabel="5 Gün" />
                        <f:selectItem itemValue="6" itemLabel="6 Gün " />
                        <f:selectItem itemValue="7" itemLabel="7 Gün" />
                        <f:selectItem itemValue="8" itemLabel="8 Gün" />
                        <f:selectItem itemValue="9" itemLabel="9 Gün" />
                        <f:selectItem itemValue="10" itemLabel="10 Gün" />
                        <f:selectItem itemValue="11" itemLabel="11 Gün" />
                        <f:selectItem itemValue="12" itemLabel="12 Gün" />
                        <f:selectItem itemValue="13" itemLabel="13 Gün" />
                        <f:selectItem itemValue="14" itemLabel="14 Gün" />
                        <f:selectItem itemValue="15" itemLabel="15 Gün" />
                        <f:selectItem itemValue="16" itemLabel="16 Gün" />
                        <f:selectItem itemValue="17" itemLabel="17 Gün" />
                        <f:selectItem itemValue="18" itemLabel="18 Gün" />
                        <f:selectItem itemValue="19" itemLabel="19 Gün" />
                        <f:selectItem itemValue="20" itemLabel="20 Gün" />
                        <f:selectItem itemValue="21" itemLabel="21 Gün" />
                        <f:selectItem itemValue="22" itemLabel="22 Gün" />
                        <f:selectItem itemValue="23" itemLabel="23 Gün" />
                        <f:selectItem itemValue="24" itemLabel="24 Gün" />
                        <f:selectItem itemValue="25" itemLabel="25 Gün" />
                        <f:selectItem itemValue="26" itemLabel="26 Gün" />
                        <f:selectItem itemValue="27" itemLabel="27 Gün" />
                        <f:selectItem itemValue="28" itemLabel="28 Gün" />
                        <f:selectItem itemValue="29" itemLabel="29 Gün" />
                        <f:selectItem itemValue="30" itemLabel="30 Gün" />
                    </h:selectOneMenu>                                                              
                    <br />
                    <h:outputText value="STOK:"/>
                    <h:outputText value="#{kiralaBean.stok}"/>
                    <br />
                    <h:outputText value="FİYAT:"/>
                    <h:outputText value="#{kiralaBean.fiyat}"/>
                    <br />
                    
                    <h:commandButton value="STOK" action="#{kiralaBean.stokver(Auris)}">
                    <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Ekonomik" />
                    </h:commandButton>
                    <h:commandButton value="FİYAT" action="#{kiralaBean.fiyatver(Auris)}">
                    <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Ekonomik" />
                    </h:commandButton>
                        
                    <h:commandButton value="KİRALA" action="#{kiralaBean.kiraver(Auris)}">
                    <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Ekonomik" />
                    </h:commandButton>
                </h:panelGrid>
            </h:form>
        </div>
	</div>   
</div>
<div class="clearfix"></div>
<div class="footer">
	Copyright  2014 | Tüm hakları İssizzler' e saklıdır.
</div>
<div class="clearfix"></div>
</h:body>
</html>

Proje/web/resimj1.xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>KÜBRA AÇIKGÖZ</title>
        <h:outputStylesheet library="css" name="demo.css"/>
    </h:head>
<h:body>
<div class="ustcizgi">
</div>

<div class="clearfix"></div>

<div class="ustserit">
	<div class="logo">
		<img src="resources/images/logo1.png"/>
	</div>
</div>

<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="serit">
	<ul id="menu">
		<li><a href="index.xhtml">ANASAYFA</a></li>
		<li>
			<a href="#">ARAÇ FİLOMUZ</a>
			<ul>
				<li><a href="luxarac.html">LUX ARAÇ</a></li>
				<li><a href="jeep.html">JEEP KİRALAMA</a></li>
				<li><a href="ekonomiklux.html">EKONOMİK LÜX</a></li>
				<li><a href="ekonomik.html">EKONOMİK</a></li>
			</ul>
		</li>
		<li>
			<a href="#">KİRALAMA DETAYI</a>
			<ul>
				<li><a href="ehliyetyas.html">EHLİYET VE YAŞ</a></li>
				<li><a href="kiralamakosullari.html">KİRALAMA KOŞULLARI</a></li>
				<li><a href="teslimat.html">TESLİMAT</a></li>
				<li><a href="sigorta.html">SİGORTA</a></li>
			</ul>
		</li>
		<li><a href="hakkimizda.html">HAKKIMIZDA</a></li>
		<li><a href="iletisim.html">İLETİŞİM</a></li>
	</ul>
</div>
<div class="clearfix"></div>
<div class="iletisim">
	<h1>LUX ARAÇ</h1>
	<div class="iletisim_form">
		<h2>PORSCHE CAYENNE</h2>
                <img class="" alt="" src="resources/images/resimj1.jpg" />
	</div>
	<div class="iletisim_bilgi">
        <br />
<h2>ARAÇ ÖZELLİKLERİ :</h2>		
<p>Marka:  PORSCHE CAYENNE</p>	
<p>Kiralama Model:  Cayenne Dizel</p>	
<p>Yıl:    2012</p>	
<p>Motor:  3000</p>	
<p>Vites:  Tiptronic Vites</p>	
<p>Kasa Tipi: Jeep</p>
<p>Yakıt Tipi: Dizel</p>
 <br />   <br />
<div class="kirala" style="margin-left:5px;">
            <h:form>
                <h:panelGrid style="width:60px; height:100px;" bgcolor="#e6edfd" columns="3" border="0">
                    <f:facet name="header">
                        <h:outputText value="Cayanne Dizel"/>
                    </f:facet>
                    <h:outputText value="GÜN:"/>
              
                      <h:selectOneMenu value = "#{kiralaBean.gun}">
                        <f:selectItem itemValue="1" itemLabel="1 Gün" />
                        <f:selectItem itemValue="2" itemLabel="2 Gün" />
                        <f:selectItem itemValue="3" itemLabel="3 Gün" />
                        <f:selectItem itemValue="4" itemLabel="4 Gün" />
                        <f:selectItem itemValue="5" itemLabel="5 Gün" />
                        <f:selectItem itemValue="6" itemLabel="6 Gün " />
                        <f:selectItem itemValue="7" itemLabel="7 Gün" />
                        <f:selectItem itemValue="8" itemLabel="8 Gün" />
                        <f:selectItem itemValue="9" itemLabel="9 Gün" />
                        <f:selectItem itemValue="10" itemLabel="10 Gün" />
                        <f:selectItem itemValue="11" itemLabel="11 Gün" />
                        <f:selectItem itemValue="12" itemLabel="12 Gün" />
                        <f:selectItem itemValue="13" itemLabel="13 Gün" />
                        <f:selectItem itemValue="14" itemLabel="14 Gün" />
                        <f:selectItem itemValue="15" itemLabel="15 Gün" />
                        <f:selectItem itemValue="16" itemLabel="16 Gün" />
                        <f:selectItem itemValue="17" itemLabel="17 Gün" />
                        <f:selectItem itemValue="18" itemLabel="18 Gün" />
                        <f:selectItem itemValue="19" itemLabel="19 Gün" />
                        <f:selectItem itemValue="20" itemLabel="20 Gün" />
                        <f:selectItem itemValue="21" itemLabel="21 Gün" />
                        <f:selectItem itemValue="22" itemLabel="22 Gün" />
                        <f:selectItem itemValue="23" itemLabel="23 Gün" />
                        <f:selectItem itemValue="24" itemLabel="24 Gün" />
                        <f:selectItem itemValue="25" itemLabel="25 Gün" />
                        <f:selectItem itemValue="26" itemLabel="26 Gün" />
                        <f:selectItem itemValue="27" itemLabel="27 Gün" />
                        <f:selectItem itemValue="28" itemLabel="28 Gün" />
                        <f:selectItem itemValue="29" itemLabel="29 Gün" />
                        <f:selectItem itemValue="30" itemLabel="30 Gün" />
                    </h:selectOneMenu>                                                              
                    <br />
                    <h:outputText value="STOK:"/>
                    <h:outputText value="#{kiralaBean.stok}"/>
                    <br />
                    <h:outputText value="FİYAT:"/>
                    <h:outputText value="#{kiralaBean.fiyat}"/>
                    <br />
                    
                    <h:commandButton value="STOK" action="#{kiralaBean.stokver(CayenneDizel)}" >
                        <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Jeep" />
                    </h:commandButton>       
                    <h:commandButton value="FİYAT" action="#{kiralaBean.fiyatver(CayenneDizel)}" >
                        <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Jeep" />
                     </h:commandButton>
                    <h:commandButton value="KİRALA" action="#{kiralaBean.kiraver(CayenneDizel)}">
                        <f:setPropertyActionListener target="#{kiralaBean.tabloAdi}" value="Jeep" />
                    </h:commandButton>

                </h:panelGrid>
            </h:form>
        </div>
	</div>
</div>
<div class="clearfix"></div>
<div class="footer">
	Copyright  2014 | Tüm hakları İssizzler' e saklıdır.
</div>
<div class="clearfix"></div>
</h:body>
</html>